version: '3'
services:
  client:
    build: ./client
    ports:
    - "127.0.0.1:3000:3000"
    environment:
    - PORT=3000
    - NODE_ENV=production
    links:
    - server
    restart: always
  server:
    build: ./server
    ports:
    - "127.0.0.1:4000:4000"
    environment:
    - PORT=4000
    - NODE_ENV=production
    links:
    - mysql
    restart: always
  mysql:
    image: mysql:5
    ports:
    - "127.0.0.1:3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=bF9zhLWryNhsUuYzRXwULDits
    - MYSQL_DATABASE=test
    restart: always
